### ISSUE TITLE
Can't use -outputDir and -inputDir with ToMap (unless Yatea file already exists)

### ISSUE THREAD

**Issue by ldeleger** [Bibliome/alvisnlp#41]
Using -outputDir and -inputDir with ToMap generates an error, the program can't find the yatea file that was generated in the outputDir, even when specifying the outputDir as inputDir.

Example on Migale:
`/projet/mig/work/textemig/software/install/alvisnlp/bin/alvisnlp -cleanTmp -verbose -log corpus/test/batch/0000/alvisnlp.log -inputDir corpus/test/batch/0000/ -inputDir corpus/test/batch/0000/output -outputDir corpus/test/batch/0000/output plans/test-output.plan`
Generates the following error:
```
[2017-11-27 10:52:10.182][entities.term-extraction.yatea] done in 586 ms
[2017-11-27 10:52:10.182][entities.term-extraction] done in 616 ms
[2017-11-27 10:52:10.182][entities.tomap] processing
[2017-11-27 10:52:10.352][alvisnlp] SEVERE org.xml.sax.SAXParseException; Premature end of file.
```
NB: this only happens the first time you run the command. If you try a second time (= the yatea output already exists), then it works.

**Comment by rbossy** [comment]
Pay attention: this one's brutal.

It's a bad combination of `-inputDir` and `inhibitCheck`.

When running for the first time, `alvisnlp` will convert the value for the parameter `yateaFile` in module `entities.tomap`. Since it is a relative path, then it will use the `-inputDir` as bases and look for an existing file.

However neither `corpus/test/batch/0000/yatea/corpus/default/xml/candidates.xml` or `corpus/test/batch/0000/output/yatea/corpus/default/xml/candidates.xml` exist. So the convertion returns `yatea/corpus/default/xml/candidates.xml` without base.

`alvisnlp` does not complain it doesn't exists because of `inhibitCheck`. When the module runs, it fails because it opens an nonexistent file.

## Solution

First, the conversion has been modified on https://github.com/Bibliome/bibliome-java-utils 8d728f5b8ee17b87e8e1640ea444c6ad448e10d3. If the file is not found in any `inputDir` then it returns the path with the first `inputDir` as a base. That's actually way better because input files will always have a base rooted on a `inputDir`.

The change has been pushed and exposed on the maven repo.

@ldeleger 
In order to function you must swap the two `-inputDir` in your command line.
